services:

  cronicle:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    hostname: cronicle
    # ports:
    #   - 3012:3012
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data/data:/opt/cronicle/data
      - ./data/logs:/opt/cronicle/logs
      - ./data/plugins:/opt/cronicle/plugins
      - ./data/scripts:/opt/cronicle/scripts
    environment:
      - SERVICE_FQDN_CRONICLE_3012
      - TZ=Europe/Rome
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:3012/api/app/ping || exit 1"]
      interval: 5s
      timeout: 1s
      retries: 3
    logging:
        driver: "json-file"
        options:
            max-size: "10m"

  filebrowser:
    image: 'filebrowser/filebrowser:latest'
    environment:
      - SERVICE_FQDN_FILEBROWSER_80
    # ports:
    #   - 3013:80
    volumes:
      - ./data/scripts:/cronicle/scripts
        # type: bind
        # source: ./data/scripts
        # target: /cronicle/scripts
        # isDirectory: true
      - type: bind
        source: ./database.db
        target: /database.db
        isDirectory: false
        content: ''

      - type: bind
        source: ./filebrowser.json
        target: /.filebrowser.json
        read_only: true
        content: "{\n  \"address\": \"0.0.0.0\",\n  \"port\": 80\n}"
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1:80'
      interval: 2s
      timeout: 10s
      retries: 15
